// <auto-generated />
using System;
using Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240630064133_ChangedEntities")]
    partial class ChangedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SavedUserAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b07dd4ae-fc21-49e6-ade5-afcb50d8c010"),
                            Apartment = "1",
                            City = "Братск",
                            CustomerId = new Guid("5b7e1118-daa3-4467-b6dd-ed5199f3f070"),
                            House = "1",
                            Street = "Советская"
                        });
                });

            modelBuilder.Entity("Identity.Entities.PaymentCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expiration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SavedUserPaymentCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3940d311-c8ab-4030-aef0-04fcb9da3cc4"),
                            CardHolderName = "IVAN IVANOV",
                            CardNumber = "1111 2222 3333 4444",
                            CustomerId = new Guid("5b7e1118-daa3-4467-b6dd-ed5199f3f070"),
                            Cvv = "111",
                            Expiration = "10/25"
                        });
                });

            modelBuilder.Entity("Identity.Entities.User", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("5b7e1118-daa3-4467-b6dd-ed5199f3f070"),
                            Birthday = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@gmail.com",
                            Name = "Test User",
                            Password = "test",
                            PhoneNumber = "+79012223344"
                        });
                });

            modelBuilder.Entity("Identity.Entities.Address", b =>
                {
                    b.HasOne("Identity.Entities.User", "User")
                        .WithMany("SavedAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Entities.PaymentCard", b =>
                {
                    b.HasOne("Identity.Entities.User", "User")
                        .WithMany("SavedPaymentCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Entities.User", b =>
                {
                    b.Navigation("SavedAddresses");

                    b.Navigation("SavedPaymentCards");
                });
#pragma warning restore 612, 618
        }
    }
}
